name: conan-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python and Conan
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install python3-pip -y
          python3 -m pip install --upgrade pip
          python3 -m pip install conan

      - name: Install Conan dependencies
        run: |
          conan install . --build=missing

      - name: Build with Conan
        run: |
          conan build .
          